title: Austin
description: >-
  Austin Liu. A dental student in Adelaide who loves Japan, trades crypto, and builds open-source projects. Welcome to my corner of the internet.
baseurl: ""
url: "https://Dingding-leo.github.io"
permalink: /posts/:title/
markdown: kramdown

author:
  name: "Austin Liu"
  email: "Austinliu234@gmail.com"

social:
  github: "Dingding-leo"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
